apiVersion: v1
kind: List
items:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: cloudformationtemplates.service-operator.aws
  spec:
    group: service-operator.aws
    names:
      kind: CloudFormationTemplate
      listKind: CloudFormationTemplateList
      plural: cloudformationtemplates
      shortNames:
      - cft
      - cfts
      - cfn
      - cfns
      - cloudformation
      singular: cloudformationtemplates
    scope: Namespaced
    version: v1alpha1

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: dynamodbs.service-operator.aws
  spec:
    group: service-operator.aws
    names:
      kind: DynamoDB
      listKind: DynamoDBList
      plural: dynamodbs
      shortNames:
      - ddb
      - ddbs
      - dynamo
      - dynamotable
      - dynamotables
      singular: dynamodbs
    scope: Namespaced
    version: v1alpha1

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: ecrrepositories.service-operator.aws
  spec:
    group: service-operator.aws
    names:
      kind: ECRRepository
      listKind: ECRRepositoryList
      plural: ecrrepositories
      shortNames:
      - ecr
      - repository
      singular: ecrrepositories
    scope: Namespaced
    version: v1alpha1

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: elasticaches.service-operator.aws
  spec:
    group: service-operator.aws
    names:
      kind: ElastiCache
      listKind: ElastiCacheList
      plural: elasticaches
      shortNames:
      - ec
      singular: elasticaches
    scope: Namespaced
    version: v1alpha1

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: s3buckets.service-operator.aws
  spec:
    group: service-operator.aws
    names:
      kind: S3Bucket
      listKind: S3BucketList
      plural: s3buckets
      shortNames:
      - s3
      - bucket
      - buckets
      singular: s3buckets
    scope: Namespaced
    version: v1alpha1

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: snssubscriptions.service-operator.aws
  spec:
    group: service-operator.aws
    names:
      kind: SNSSubscription
      listKind: SNSSubscriptionList
      plural: snssubscriptions
      shortNames:
      - subscription
      singular: snssubscriptions
    scope: Namespaced
    version: v1alpha1

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: snstopics.service-operator.aws
  spec:
    group: service-operator.aws
    names:
      kind: SNSTopic
      listKind: SNSTopicList
      plural: snstopics
      shortNames:
      - sns
      - topic
      - topics
      singular: snstopics
    scope: Namespaced
    version: v1alpha1

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: sqsqueues.service-operator.aws
  spec:
    group: service-operator.aws
    names:
      kind: SQSQueue
      listKind: SQSQueueList
      plural: sqsqueues
      shortNames:
      - sqs
      - queue
      - queues
      singular: sqsqueues
    scope: Namespaced
    version: v1alpha1
