apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "aws-service-operator.fullname" . }}
  labels:
{{ include "aws-service-operator.helmStandardLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{ include "aws-service-operator.helmPodLabels" . | indent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
        {{- end }}
      labels:
{{ include "aws-service-operator.helmPodLabels" . | indent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{ end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end  }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "aws-service-operator.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      containers:
        - name: aws-service-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - server
            {{ if .Values.operator }}
            {{ if .Values.operator.accountId }}
            - --account-id={{ .Values.operator.accountId }}
            {{- end }}
            {{- if .Values.operator.bucket }}
            - --bucket={{ .Values.operator.bucket }}
            {{- end }}
            {{- if .Values.operator.clusterName }}
            - --cluster-name={{ .Values.operator.clusterName }}
            {{- end }}
            {{- if .Values.operator.config }}
            - --config={{ .Values.operator.config }}
            {{- end }}
            {{- if .Values.operator.kubeconfig }}
            - --kubeconfig={{ .Values.operator.kubeconfig }}
            {{- end }}
            {{- if .Values.operator.logfile }}
            - --logfile={{ .Values.operator.logfile }}
            {{- end }}
            {{- if .Values.operator.loglevel }}
            - --loglevel={{ .Values.operator.loglevel }}
            {{- end }}
            {{- if .Values.operator.region }}
            - --region={{ .Values.operator.region }}
            {{- end }}
            {{- if .Values.operator.resources }}
            - --resources={{ .Values.operator.resources }}
            {{- end }}
            {{- range $key, $value := .Values.extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- if .Values.affinity }}
          affinity:
{{ toYaml .Values.affinity | indent 12 }}
          {{- end }}
          {{- if .Values.extraEnv}}
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
          {{- if .Values.tolerations }}
          tolerations:
{{ toYaml .Values.tolerations | indent 12 }}
          {{- end }}
{{- if .Values.extraVolumeMounts }}
          volumeMounts:
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
{{- if .Values.extraVolumes }}
      volumes:
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
